"""ZIP Packager.

Bundles all generated report files into a single downloadable ZIP archive
with an included README explaining the contents.
"""

from __future__ import annotations

import logging
import zipfile
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

_FILE_DESCRIPTIONS: dict[str, str] = {
    ".html": "Interactive HTML report (open in any browser)",
    ".pdf": "Print-ready PDF report",
    ".ipynb": "Runnable Jupyter notebook with full analysis code",
    ".css": "Stylesheet for the HTML report",
    ".csv": "Exported data file",
    ".json": "Structured data export",
    ".pkl": "Serialised model artifact",
    ".joblib": "Serialised model artifact (joblib format)",
}


def _generate_readme(file_paths: list[str]) -> str:
    """Generate a README.txt describing the ZIP contents.

    Args:
        file_paths: List of file path strings included in the archive.

    Returns:
        README text content.
    """
    lines = [
        "AutoDS Analysis Package",
        "=" * 40,
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "Contents:",
        "-" * 40,
    ]

    for fp in sorted(file_paths):
        name = Path(fp).name
        suffix = Path(fp).suffix.lower()
        description = _FILE_DESCRIPTIONS.get(suffix, "Analysis artifact")
        lines.append(f"  {name}")
        lines.append(f"    {description}")
        lines.append("")

    lines.extend([
        "-" * 40,
        "",
        "Quick Start:",
        "  1. Open report.html in your browser for the interactive report.",
        "  2. Open analysis_notebook.ipynb in Jupyter to re-run the analysis.",
        "  3. Open executive_summary.html for a concise stakeholder summary.",
        "",
        "Notes:",
        "  - The HTML report includes embedded Plotly charts (requires internet",
        "    for the Plotly CDN on first load).",
        "  - The notebook is self-contained; update the DATA_PATH variable in",
        "    cell 2 to point at your dataset.",
        "",
        "Generated by AutoDS - Autonomous Data Science Platform",
    ])

    return "\n".join(lines)


def create_zip_package(
    file_paths: list[str],
    output_dir: str,
    session_id: str = "session",
) -> str:
    """Bundle report files into a downloadable ZIP archive.

    Includes a README.txt explaining the archive contents. Files are
    stored at the root level of the archive (no nested directories).

    Args:
        file_paths: List of absolute or relative file path strings to include.
        output_dir: Directory to write the ZIP file into.
        session_id: Session identifier used in the ZIP filename.

    Returns:
        Absolute path to the created ZIP file.
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Sanitise session_id for filename safety
    safe_session = "".join(
        c if c.isalnum() or c in ("-", "_") else "_"
        for c in str(session_id)
    )
    zip_path = out_dir / f"autods_{safe_session}.zip"

    existing_paths = [p for p in file_paths if Path(p).exists()]

    if not existing_paths:
        logger.warning("No files found for ZIP packaging.")
        return ""

    readme_text = _generate_readme(existing_paths)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fp in existing_paths:
            p = Path(fp)
            zf.write(p, arcname=p.name)
            logger.debug("Added %s to ZIP archive.", p.name)

        zf.writestr("README.txt", readme_text)

    logger.info(
        "ZIP package created at %s (%d files).",
        zip_path,
        len(existing_paths) + 1,
    )
    return str(zip_path)
