"""Deployment Agent.

Generates a self-contained FastAPI microservice package from the trained
best model:
  - api.py           FastAPI app with /health, /predict, /predict/batch
  - schemas.py       Pydantic request / response models
  - requirements.txt Minimal production dependencies
  - Dockerfile       Multi-stage Python 3.11 build
  - README.md        Quick-start instructions

All generated text is stored in state["deployment_artifacts"] and
written to outputs/{session_id}/deployment/.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from core.state import AutoDSState

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Type-inference helper
# ---------------------------------------------------------------------------
_DTYPE_TO_PYTHON: dict[str, str] = {
    "int64": "int", "int32": "int", "int16": "int", "int8": "int",
    "float64": "float", "float32": "float",
    "bool": "bool",
    "object": "str", "string": "str",
    "category": "str",
}


def _python_type(dtype: str) -> str:
    return _DTYPE_TO_PYTHON.get(dtype, "Any")


def _safe_get(state: AutoDSState, *keys: str, default: Any = None) -> Any:
    for key in keys:
        val = state.get(key)  # type: ignore[arg-type]
        if val is not None:
            return val
    return default


# ---------------------------------------------------------------------------
# api.py generator
# ---------------------------------------------------------------------------
def _generate_api_py(
    features: list[str],
    target: str,
    problem_type: str,
    model_path: str,
    model_name: str,
) -> str:
    """Generate FastAPI application source code.

    Args:
        features: List of input feature names.
        target: Target column name.
        problem_type: classification or regression.
        model_path: Path to the saved model artifact.
        model_name: Display name of the best model.

    Returns:
        Python source code string for api.py.
    """
    is_clf = problem_type == "classification"
    proba_block = (
        "    if hasattr(model, 'predict_proba'):\n"
        "        proba = float(model.predict_proba(df)[0].max())\n"
        "    else:\n"
        "        proba = None\n"
    ) if is_clf else "    proba = None\n"

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f'''"""AutoDS-generated FastAPI prediction service.

Model: {model_name}
Target: {target}
Problem type: {problem_type}
Generated: {generated_at}
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

import joblib
import pandas as pd
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import JSONResponse

from schemas import BatchPredictionResponse, PredictionRequest, PredictionResponse

MODEL_PATH = Path(r"{model_path}")
FEATURES = {json.dumps(features)}

app = FastAPI(
    title="AutoDS Prediction API",
    description="Generated by AutoDS — Autonomous Data Science Platform",
    version="1.0.0",
)

# Load model once at startup
# SECURITY: Uses joblib instead of pickle to reduce deserialization risks.
# Never load model files from untrusted sources.
_model = None
try:
    _loaded = joblib.load(MODEL_PATH)
    _model = _loaded["model"] if isinstance(_loaded, dict) else _loaded
except FileNotFoundError:
    pass  # Will raise 503 on first request


def _get_model() -> Any:
    if _model is None:
        raise HTTPException(status_code=503, detail="Model not loaded. Check MODEL_PATH.")
    return _model


@app.get("/health", tags=["ops"])
def health() -> dict:
    """Liveness probe."""
    return {{"status": "ok", "model": "{model_name}", "target": "{target}"}}


@app.post("/predict", response_model=PredictionResponse, tags=["inference"])
def predict(request: PredictionRequest) -> PredictionResponse:
    """Return a single prediction from a JSON payload."""
    model = _get_model()
    row = {{k: v for k, v in request.model_dump().items() if k in FEATURES}}
    df = pd.DataFrame([row])
    prediction = model.predict(df)[0]
{proba_block}
    return PredictionResponse(
        prediction=prediction,
        probability=proba,
        model_name="{model_name}",
    )


@app.post("/predict/batch", response_model=BatchPredictionResponse, tags=["inference"])
async def predict_batch(file: UploadFile = File(...)) -> BatchPredictionResponse:
    """Return predictions for a CSV file upload."""
    model = _get_model()
    contents = await file.read()
    df = pd.read_csv(io.BytesIO(contents))
    missing = [c for c in FEATURES if c not in df.columns]
    if missing:
        raise HTTPException(
            status_code=422,
            detail=f"Missing required columns: {{missing}}",
        )
    preds = model.predict(df[FEATURES]).tolist()
    probas: list = [None] * len(preds)
    if hasattr(model, "predict_proba"):
        probas = model.predict_proba(df[FEATURES]).max(axis=1).tolist()
    results = [
        {{"prediction": p, "probability": pr, "model_name": "{model_name}"}}
        for p, pr in zip(preds, probas)
    ]
    return BatchPredictionResponse(predictions=results, count=len(results))
'''


# ---------------------------------------------------------------------------
# schemas.py generator
# ---------------------------------------------------------------------------
def _generate_schemas_py(
    features: list[str],
    schema_info: dict,
    problem_type: str,
) -> str:
    """Generate Pydantic schema source code for request/response models.

    Args:
        features: List of feature names.
        schema_info: Schema metadata with column dtype info.
        problem_type: classification or regression.

    Returns:
        Python source code string for schemas.py.
    """
    columns_meta: list[dict] = schema_info.get("columns", [])
    dtype_map: dict[str, str] = {
        col.get("name", ""): col.get("dtype", "object")
        for col in columns_meta
        if col.get("name")
    }

    if features:
        field_lines = "\n    ".join(
            f'{f}: {_python_type(dtype_map.get(f, "object"))} = ...'
            for f in features
        )
    else:
        field_lines = "pass"

    proba_field = "    probability: float | None = None\n" if problem_type == "classification" else ""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f'''"""Pydantic schemas for the AutoDS prediction API.

Generated: {generated_at}
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field


class PredictionRequest(BaseModel):
    """One row of feature values for a single prediction."""
    {field_lines}


class PredictionResponse(BaseModel):
    """Prediction result for a single request."""
    prediction: Any
{proba_field}    model_name: str
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class BatchPredictionResponse(BaseModel):
    """Prediction results for a CSV batch request."""
    predictions: list[dict[str, Any]]
    count: int
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
'''


# ---------------------------------------------------------------------------
# requirements.txt generator
# ---------------------------------------------------------------------------
def _generate_requirements() -> str:
    """Generate minimal production requirements.txt."""
    return (
        "fastapi>=0.110.0\n"
        "uvicorn[standard]>=0.27.0\n"
        "pydantic>=2.6.0\n"
        "scikit-learn>=1.4.0\n"
        "pandas>=2.1.0\n"
        "numpy>=1.26.0\n"
        "joblib>=1.3.0\n"
        "python-multipart>=0.0.9\n"
    )


# ---------------------------------------------------------------------------
# Dockerfile generator
# ---------------------------------------------------------------------------
def _generate_dockerfile(model_path: str) -> str:
    """Generate multi-stage Dockerfile for the prediction API.

    Args:
        model_path: Path to the saved model artifact.

    Returns:
        Dockerfile content string.
    """
    model_filename = Path(model_path).name
    return f"""# Multi-stage build — AutoDS generated Dockerfile
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \\
    && pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim AS runtime
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY api.py schemas.py {model_filename} ./
EXPOSE 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
"""


# ---------------------------------------------------------------------------
# README.md generator
# ---------------------------------------------------------------------------
def _generate_readme(model_name: str, features: list[str], target: str) -> str:
    """Generate quick-start README for the deployment package.

    Args:
        model_name: Best model display name.
        features: Input feature names.
        target: Target column name.

    Returns:
        Markdown README content string.
    """
    sample_payload = {f: "<value>" for f in features[:5]}
    sample_json = json.dumps(sample_payload, indent=2)
    feature_list_md = "\n".join(f"- `{f}`" for f in features[:20])
    ellipsis = "..." if len(features) > 20 else ""

    return f"""# AutoDS Prediction API

Model: **{model_name}**
Target: `{target}`
Generated by AutoDS — Autonomous Data Science Platform

## Quick Start

### Run locally

```bash
pip install -r requirements.txt
uvicorn api:app --reload
```

API docs available at <http://localhost:8000/docs>

### Run with Docker

```bash
docker build -t autods-api .
docker run -p 8000:8000 autods-api
```

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | /health | Liveness probe |
| POST | /predict | Single-row JSON prediction |
| POST | /predict/batch | CSV file batch prediction |

## Example single prediction

```bash
curl -X POST http://localhost:8000/predict \\
  -H "Content-Type: application/json" \\
  -d '{sample_json}'
```

## Features required

{feature_list_md}
{ellipsis}
"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def generate_deployment(state: AutoDSState) -> AutoDSState:
    """Generate FastAPI deployment package and update state.

    Produces: api.py, schemas.py, requirements.txt, Dockerfile, README.md
    Writes to: outputs/{session_id}/deployment/

    Args:
        state: Current pipeline state.

    Returns:
        Updated state with deployment_artifacts, deployment_path, api_endpoint_url.
    """
    state["current_step"] = "deployment"
    state["completed_steps"] = state.get("completed_steps", []) + ["deployment"]

    session_id = state.get("session_id", "session_unknown")
    best_model = _safe_get(state, "best_model", "best_model_name", default="best_model")
    model_path = state.get("best_model_path", "model.pkl")
    features: list[str] = _safe_get(state, "feature_list", "features_selected", default=[])
    target = state.get("target_column", "target")
    problem_type = state.get("problem_type", "classification")
    schema_info = state.get("schema_info") or {}

    out_dir = Path("outputs") / session_id / "deployment"
    out_dir.mkdir(parents=True, exist_ok=True)

    artifacts: dict[str, str] = {}

    generators = [
        ("api.py", lambda: _generate_api_py(features, target, problem_type, model_path, best_model)),
        ("schemas.py", lambda: _generate_schemas_py(features, schema_info, problem_type)),
        ("requirements.txt", _generate_requirements),
        ("Dockerfile", lambda: _generate_dockerfile(model_path)),
        ("README.md", lambda: _generate_readme(best_model, features, target)),
    ]

    for filename, gen_fn in generators:
        try:
            artifacts[filename] = gen_fn()
        except Exception as exc:
            logger.error("%s generation failed: %s", filename, exc, exc_info=True)
            state["errors"] = state.get("errors", []) + [{
                "step": "deployment",
                "type": f"{filename}_failed",
                "detail": str(exc),
            }]

    # Write all successfully generated artifacts to disk
    for filename, content in artifacts.items():
        try:
            (out_dir / filename).write_text(content, encoding="utf-8")
        except Exception as exc:
            logger.error("Failed to write %s: %s", filename, exc, exc_info=True)
            state["errors"] = state.get("errors", []) + [{
                "step": "deployment",
                "type": "write_failed",
                "detail": f"{filename}: {exc}",
            }]

    state["deployment_artifacts"] = artifacts
    state["deployment_path"] = str(out_dir)
    state["api_endpoint_url"] = "http://localhost:8000"
    logger.info(
        "Deployment artifacts generated: %s -> %s",
        list(artifacts.keys()), out_dir,
    )
    return state
